fix import of color
I run into this issue when running vitest for my project:
```
 FAIL  src/components/header/Header.test.tsx [ src/components/header/Header.test.tsx ]
SyntaxError: Unexpected token 'export'
 ❯ Object.compileFunction node:vm:360:18
 ❯ Object.<anonymous> node_modules/@jy95/material-ui-image/lib/components/Image/Image.js:16:38

Module /workspaces/viseron/frontend/node_modules/@mui/material/colors/common.js:5 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "@mui/material" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.

As a temporary workaround you can try to inline the package by updating your config:

// vitest.config.js
export default {
  test: {
    deps: {
      inline: [
        "@mui/material"
      ]
    }
  }
}
```

It seems that this 4-level import is causing this issue